language: generic

dist: bionic
sudo: required

services:
  - docker

env:
  global:
    - CIRP_GITHUB_REPO_SLUG="nurupo/vlc-pause-click-plugin-nightly-builds"

if: (branch != nightly && type != cron) || (branch == nightly && type == cron)

matrix:
  include:
    - stage: Build
      os: linux
      env: TARGET=Linux   VLC_VERSION=2.1 DEBIAN=wheezy-backports
    - os: linux
      env: TARGET=Linux   VLC_VERSION=2.2 DEBIAN=jessie
    - os: linux
      env: TARGET=Linux   VLC_VERSION=3.0 DEBIAN=stretch
    - os: linux
      env: TARGET=Windows VLC_VERSION=2.1
    - os: linux
      env: TARGET=Windows VLC_VERSION=2.2
    - os: linux
      env: TARGET=Windows VLC_VERSION=3.0
    - os: linux
      env: TARGET=Windows VLC_VERSION=4.0
      script:
        - .travis/script.sh
        - .travis/cirp/cleanup1.sh
        - .travis/cirp/store.sh "$TRAVIS_BUILD_DIR/artifacts"
        - .travis/cirp/cleanup2.sh
    - os: osx
      env: TARGET=macOS   VLC_VERSION=2.1
      language: c
      osx_image: xcode10.2
    - os: osx
      env: TARGET=macOS   VLC_VERSION=2.2
      language: c
      osx_image: xcode10.2
    - os: osx
      env: TARGET=macOS   VLC_VERSION=3.0
      language: c
      osx_image: xcode10.2
    - os: osx
      env: TARGET=macOS   VLC_VERSION=4.0
      language: c
      osx_image: xcode10.2
      script:
        - .travis/script.sh
        - .travis/cirp/cleanup1.sh
        - .travis/cirp/store.sh "$TRAVIS_BUILD_DIR/artifacts"
        - .travis/cirp/cleanup2.sh
    - stage: "Nightly publishing"
      if: type == cron
      script:
        - export ARTIFACTS_DIR="$(mktemp -d)"
        - .travis/cirp/collect.sh "$ARTIFACTS_DIR"
        - .travis/cirp/cleanup4.sh
        - .travis/cirp/publish.sh "$ARTIFACTS_DIR"
        - .travis/cirp/cleanup5.sh

script:
  - .travis/script.sh
  - .travis/cirp/cleanup1.sh
  - .travis/cirp/cleanup2.sh

deploy:
  provider: releases
  api_key:
    secure: BEBtgDclwqKqi1NWY26Af/5DalWJYFlxV36QMEC6EKajA5tv2GBR0nyjIpzG+wNeuqZitqYQaOG60F/UPD1xjbN1ZXdN4byuSaMKRUseO2H/7r3StMlTL3knVce4giIwaEe7Q05QtiV+3zLTcAxsEmzehQJZZpnYK0KXGqRyC/U=
  file: artifacts/vlc-*-macosx.zip
  file_glob: true
  skip_cleanup: true
  on:
    condition: $TARGET == macOS
    repo: nurupo/vlc-pause-click-plugin
    tags: true
