language: generic

sudo: required

services:
  - docker

matrix:
  include:
    - os: linux
      env: TARGET=Linux   VLC_VERSION=2.1 DEBIAN=wheezy-backports
    - os: linux
      env: TARGET=Linux   VLC_VERSION=2.2 DEBIAN=jessie
    - os: linux
      env: TARGET=Linux   VLC_VERSION=3.0 DEBIAN=stretch
    - os: linux
      env: TARGET=Windows VLC_VERSION=2.1
    - os: linux
      env: TARGET=Windows VLC_VERSION=2.2
    - os: linux
      env: TARGET=Windows VLC_VERSION=3.0
    - os: linux
      env: TARGET=Windows VLC_VERSION=4.0
    - os: osx
      env: TARGET=macOS   VLC_VERSION=2.1
      language: c
      osx_image: xcode7.3
    - os: osx
      env: TARGET=macOS   VLC_VERSION=2.2
      language: c
      osx_image: xcode7.3
    - os: osx
      env: TARGET=macOS   VLC_VERSION=3.0
      language: c
      osx_image: xcode7.3
    - os: osx
      env: TARGET=macOS   VLC_VERSION=4.0
      language: c
      osx_image: xcode7.3

script:
  - ./.travis/script.sh

deploy:
  provider: releases
  api_key:
    secure: BEBtgDclwqKqi1NWY26Af/5DalWJYFlxV36QMEC6EKajA5tv2GBR0nyjIpzG+wNeuqZitqYQaOG60F/UPD1xjbN1ZXdN4byuSaMKRUseO2H/7r3StMlTL3knVce4giIwaEe7Q05QtiV+3zLTcAxsEmzehQJZZpnYK0KXGqRyC/U=
  file: vlc-*-macosx.zip
  file_glob: true
  skip_cleanup: true
  on:
    condition: $TARGET == macOS
    repo: nurupo/vlc-pause-click-plugin
    tags: true
